// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by localization_gen

import 'package:flutter/widgets.dart';

/// Strongly-typed localization class
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  /// Get the localization instance from context
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  /// All supported locales
  static const supportedLocales = [
    Locale('en'),
    Locale('id'),
  ];

  /// Access login translations
  _Login get login => _Login(locale);

  /// Access register translations
  _Register get register => _Register(locale);

  /// Access errors translations
  _Errors get errors => _Errors(locale);

  /// Access profile translations
  _Profile get profile => _Profile(locale);

  /// Access preferences translations
  _Preferences get preferences => _Preferences(locale);

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Settings';
      case 'id': return 'Pengaturan';
      default: return 'Settings';
    }
  }


  String get welcome {
    switch (locale.languageCode) {
      case 'en': return 'Welcome to Localization Gen!';
      case 'id': return 'Selamat datang di Localization Gen!';
      default: return 'Welcome to Localization Gen!';
    }
  }


  String welcome_user({required String name}) {
    switch (locale.languageCode) {
      case 'en': return 'Welcome, $name!';
      case 'id': return 'Selamat datang, $name!';
      default: return 'Welcome, $name!';
    }
  }


  String item_count({required String count}) {
    switch (locale.languageCode) {
      case 'en': return 'You have $count items';
      case 'id': return 'Anda memiliki $count item';
      default: return 'You have $count items';
    }
  }


  String discount({required String value}) {
    switch (locale.languageCode) {
      case 'en': return 'Discount $value%';
      case 'id': return 'Diskon $value%';
      default: return 'Discount $value%';
    }
  }


  String get hello {
    switch (locale.languageCode) {
      case 'en': return 'Hello';
      case 'id': return 'Halo';
      default: return 'Hello';
    }
  }


  String get goodbye {
    switch (locale.languageCode) {
      case 'en': return 'Goodbye';
      case 'id': return 'Selamat tinggal';
      default: return 'Goodbye';
    }
  }


  String get yes {
    switch (locale.languageCode) {
      case 'en': return 'Yes';
      case 'id': return 'Ya';
      default: return 'Yes';
    }
  }


  String get no {
    switch (locale.languageCode) {
      case 'en': return 'No';
      case 'id': return 'Tidak';
      default: return 'No';
    }
  }


  String get save {
    switch (locale.languageCode) {
      case 'en': return 'Save';
      case 'id': return 'Simpan';
      default: return 'Save';
    }
  }


  String get cancel {
    switch (locale.languageCode) {
      case 'en': return 'Cancel';
      case 'id': return 'Batal';
      default: return 'Cancel';
    }
  }


}

/// Translations for login namespace
class _Login {
  _Login(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Login';
      case 'id': return 'Masuk';
      default: return 'Login';
    }
  }


  String get email {
    switch (locale.languageCode) {
      case 'en': return 'Email';
      case 'id': return 'Email';
      default: return 'Email';
    }
  }


  String get password {
    switch (locale.languageCode) {
      case 'en': return 'Password';
      case 'id': return 'Kata Sandi';
      default: return 'Password';
    }
  }


  String get button {
    switch (locale.languageCode) {
      case 'en': return 'Sign In';
      case 'id': return 'Masuk';
      default: return 'Sign In';
    }
  }


  String get forgot_password {
    switch (locale.languageCode) {
      case 'en': return 'Forgot Password?';
      case 'id': return 'Lupa Kata Sandi?';
      default: return 'Forgot Password?';
    }
  }


}

/// Translations for register namespace
class _Register {
  _Register(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Register';
      case 'id': return 'Daftar';
      default: return 'Register';
    }
  }


  String get button {
    switch (locale.languageCode) {
      case 'en': return 'Sign Up';
      case 'id': return 'Buat Akun';
      default: return 'Sign Up';
    }
  }


  String get terms_accept {
    switch (locale.languageCode) {
      case 'en': return 'I accept the terms and conditions';
      case 'id': return 'Saya menerima syarat dan ketentuan';
      default: return 'I accept the terms and conditions';
    }
  }


}

/// Translations for errors namespace
class _Errors {
  _Errors(this.locale);

  final Locale locale;

  String get invalid_email {
    switch (locale.languageCode) {
      case 'en': return 'Invalid email address';
      case 'id': return 'Alamat email tidak valid';
      default: return 'Invalid email address';
    }
  }


  String get weak_password {
    switch (locale.languageCode) {
      case 'en': return 'Password is too weak';
      case 'id': return 'Kata sandi terlalu lemah';
      default: return 'Password is too weak';
    }
  }


  String get user_not_found {
    switch (locale.languageCode) {
      case 'en': return 'User not found';
      case 'id': return 'Pengguna tidak ditemukan';
      default: return 'User not found';
    }
  }


}

/// Translations for profile namespace
class _Profile {
  _Profile(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Profile';
      case 'id': return 'Profil';
      default: return 'Profile';
    }
  }


  String get edit_profile {
    switch (locale.languageCode) {
      case 'en': return 'Edit Profile';
      case 'id': return 'Edit Profil';
      default: return 'Edit Profile';
    }
  }


  String get change_password {
    switch (locale.languageCode) {
      case 'en': return 'Change Password';
      case 'id': return 'Ubah Kata Sandi';
      default: return 'Change Password';
    }
  }


}

/// Translations for preferences namespace
class _Preferences {
  _Preferences(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Preferences';
      case 'id': return 'Preferensi';
      default: return 'Preferences';
    }
  }


  String get language {
    switch (locale.languageCode) {
      case 'en': return 'Language';
      case 'id': return 'Bahasa';
      default: return 'Language';
    }
  }


  String get theme {
    switch (locale.languageCode) {
      case 'en': return 'Theme';
      case 'id': return 'Tema';
      default: return 'Theme';
    }
  }


  String get notifications {
    switch (locale.languageCode) {
      case 'en': return 'Notifications';
      case 'id': return 'Notifikasi';
      default: return 'Notifications';
    }
  }


}

/// Localization delegate for AppLocalizations
class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .map((l) => l.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

/// Extension for easy access
extension AppLocalizationsExtension on AppLocalizations {
  static const delegate = AppLocalizationsDelegate();
}

