// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by localization_gen

import 'package:flutter/widgets.dart';

/// Strongly-typed localization class
class CoreLocalizations {
  CoreLocalizations(this.locale);

  final Locale locale;

  /// Get the localization instance from context
  static CoreLocalizations of(BuildContext context) {
    return Localizations.of<CoreLocalizations>(context, CoreLocalizations)!;
  }

  /// All supported locales
  static const supportedLocales = [Locale('en'), Locale('id')];

  String get save {
    switch (locale.languageCode) {
      case 'en':
        return 'Save';
      case 'id':
        return 'Simpan';
      default:
        return 'Save';
    }
  }

  String get cancel {
    switch (locale.languageCode) {
      case 'en':
        return 'Cancel';
      case 'id':
        return 'Batal';
      default:
        return 'Cancel';
    }
  }

  String get delete {
    switch (locale.languageCode) {
      case 'en':
        return 'Delete';
      case 'id':
        return 'Hapus';
      default:
        return 'Delete';
    }
  }

  String get confirm {
    switch (locale.languageCode) {
      case 'en':
        return 'Confirm';
      case 'id':
        return 'Konfirmasi';
      default:
        return 'Confirm';
    }
  }

  String get close {
    switch (locale.languageCode) {
      case 'en':
        return 'Close';
      case 'id':
        return 'Tutup';
      default:
        return 'Close';
    }
  }

  String get loading {
    switch (locale.languageCode) {
      case 'en':
        return 'Loading...';
      case 'id':
        return 'Memuat...';
      default:
        return 'Loading...';
    }
  }

  String get error {
    switch (locale.languageCode) {
      case 'en':
        return 'An error occurred';
      case 'id':
        return 'Terjadi kesalahan';
      default:
        return 'An error occurred';
    }
  }

  String get retry {
    switch (locale.languageCode) {
      case 'en':
        return 'Retry';
      case 'id':
        return 'Coba Lagi';
      default:
        return 'Retry';
    }
  }

  String get no_data {
    switch (locale.languageCode) {
      case 'en':
        return 'No data available';
      case 'id':
        return 'Tidak ada data';
      default:
        return 'No data available';
    }
  }

  String get refresh {
    switch (locale.languageCode) {
      case 'en':
        return 'Refresh';
      case 'id':
        return 'Muat Ulang';
      default:
        return 'Refresh';
    }
  }
}

/// Localization delegate for CoreLocalizations
class CoreLocalizationsDelegate
    extends LocalizationsDelegate<CoreLocalizations> {
  const CoreLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return CoreLocalizations.supportedLocales
        .map((l) => l.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<CoreLocalizations> load(Locale locale) async {
    return CoreLocalizations(locale);
  }

  @override
  bool shouldReload(CoreLocalizationsDelegate old) => false;
}

/// Extension for easy access
extension CoreLocalizationsExtension on CoreLocalizations {
  static const delegate = CoreLocalizationsDelegate();
}
