/// Tests for DartWriter.
///
/// Covers all Dart code generation functionality.

import 'package:test/test.dart';
import 'package:localization_gen/src/writer/dart_writer.dart';
import 'package:localization_gen/src/model/localization_item.dart';

void main() {
  group('DartWriter', () {
    late DartWriter writer;

    setUp(() {
      writer = DartWriter(
        className: 'TestLocalizations',
        useContext: true,
        nullable: false,
      );
    });

    group('generate()', () {
      test('generates valid Dart code with class definition', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Hello',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('class TestLocalizations'));
        expect(code, contains('String get hello'));
        expect(code, contains('Hello'));
      });

      test('generates proper imports', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains("import 'package:flutter/widgets.dart'"));
      });

      test('generates supportedLocales list', () {
        final locales = [
          LocaleData(locale: 'en', items: {}),
          LocaleData(locale: 'id', items: {}),
        ];

        final code = writer.generate(locales);

        expect(code, contains('static const supportedLocales'));
        expect(code, contains("Locale('en')"));
        expect(code, contains("Locale('id')"));
      });

      test('generates GENERATED CODE header', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains('GENERATED CODE - DO NOT MODIFY'));
        expect(code, contains('Generated by localization_gen'));
      });
    });

    group('Simple Translations', () {
      test('generates getter for simple string', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Hello',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String get hello'));
        expect(code, contains("return 'Hello'"));
      });

      test('generates switch statement for multiple locales', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Hello',
                parameters: [],
              ),
            },
          ),
          LocaleData(
            locale: 'id',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Halo',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('switch (locale.languageCode)'));
        expect(code, contains("case 'en':"));
        expect(code, contains("case 'id':"));
      });
    });

    group('Parameters', () {
      test('generates method with single parameter', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'greeting': LocalizationItem(
                key: 'greeting',
                value: 'Hello, {name}!',
                parameters: ['name'],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String greeting({'));
        expect(code, contains('required String name'));
      });

      test('generates method with multiple parameters', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'message': LocalizationItem(
                key: 'message',
                value: '{user} sent {count} messages',
                parameters: ['user', 'count'],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String message({'));
        expect(code, contains('required String user'));
        expect(code, contains('required String count'));
      });
    });

    group('Nested Structure', () {
      test('generates nested classes for dot notation', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'auth.login': LocalizationItem(
                key: 'auth.login',
                value: 'Login',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('class _Auth'));
        expect(code, contains('_Auth get auth'));
      });

      test('generates deep nesting', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'app.auth.login.title': LocalizationItem(
                key: 'app.auth.login.title',
                value: 'Login',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('class _App'));
        expect(code, contains('class _AppAuth'));
        expect(code, contains('class _AppAuthLogin'));
      });
    });

    group('Configuration', () {
      test('respects useContext = true', () {
        final writerWithContext = DartWriter(
          className: 'TestLocalizations',
          useContext: true,
        );

        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writerWithContext.generate(locales);

        expect(code, contains('static TestLocalizations of(BuildContext'));
      });

      test('respects useContext = false', () {
        final writerWithoutContext = DartWriter(
          className: 'TestLocalizations',
          useContext: false,
        );

        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writerWithoutContext.generate(locales);

        expect(code, isNot(contains('static TestLocalizations of(')));
      });

      test('respects nullable = true', () {
        final writerNullable = DartWriter(
          className: 'TestLocalizations',
          nullable: true,
          useContext: true,
        );

        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writerNullable.generate(locales);

        expect(code, contains('TestLocalizations?'));
      });
    });

    group('Delegate Generation', () {
      test('generates delegate class', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains('class TestLocalizationsDelegate'));
        expect(code, contains('extends LocalizationsDelegate'));
      });

      test('generates load method', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains('Future<TestLocalizations> load'));
      });
    });
  });
}
