/// Tests for DartWriter.
///
/// Covers all Dart code generation functionality.
library;

import 'package:test/test.dart';
import 'package:localization_gen/src/writer/dart_writer.dart';
import 'package:localization_gen/src/model/localization_item.dart';
import 'package:localization_gen/src/model/field_rename.dart';

void main() {
  group('DartWriter', () {
    late DartWriter writer;

    setUp(() {
      writer = DartWriter(
        className: 'TestLocalizations',
        fieldRename: FieldRename.camel,
      );
    });

    group('generate()', () {
      test('generates valid Dart code with class definition', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Hello',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('class TestLocalizations'));
        expect(code, contains('String get hello'));
        expect(code, contains('Hello'));
      });

      test('generates proper imports', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains("import 'package:flutter/widgets.dart'"));
      });

      test('generates supportedLocales list', () {
        final locales = [
          LocaleData(locale: 'en', items: {}),
          LocaleData(locale: 'id', items: {}),
        ];

        final code = writer.generate(locales);

        expect(code, contains('static const supportedLocales'));
        expect(code, contains("Locale('en')"));
        expect(code, contains("Locale('id')"));
      });

      test('generates GENERATED CODE header', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains('GENERATED CODE - DO NOT MODIFY'));
        expect(code, contains('Generated by localization_gen'));
      });
    });

    group('Simple Translations', () {
      test('generates getter for simple string', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Hello',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String get hello'));
        // New output uses the shared lookup helper, no per-getter switch.
        expect(code, contains("return _root._t(\"hello\""));
      });

      test(
          'generates translation tables for multiple locales (dictionary-first)',
          () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Hello',
                parameters: [],
              ),
            },
          ),
          LocaleData(
            locale: 'id',
            items: {
              'hello': LocalizationItem(
                key: 'hello',
                value: 'Halo',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('static const Map<String, String> _t_en'));
        expect(code, contains('static const Map<String, String> _t_id'));
        expect(code, contains('"hello": \'Hello\''));
        expect(code, contains('"hello": \'Halo\''));

        // Ensure we don't emit per-getter switches anymore.
        expect(code, isNot(contains('switch (locale.languageCode)')));
      });
    });

    group('Parameters', () {
      test('generates method with single parameter', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'greeting': LocalizationItem(
                key: 'greeting',
                value: 'Hello, {name}!',
                parameters: ['name'],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String greeting({'));
        expect(code, contains('required String name'));
      });

      test('generates method with multiple parameters', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'message': LocalizationItem(
                key: 'message',
                value: '{user} sent {count} messages',
                parameters: ['user', 'count'],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String message({'));
        expect(code, contains('required String user'));
        expect(code, contains('required String count'));
      });
    });

    group('Nested Structure', () {
      test('generates nested classes for dot notation', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'auth.login': LocalizationItem(
                key: 'auth.login',
                value: 'Login',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('class _Auth'));
        expect(code, contains('_Auth get auth'));
      });

      test('generates deep nesting', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'app.auth.login.title': LocalizationItem(
                key: 'app.auth.login.title',
                value: 'Login',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('class _App'));
        expect(code, contains('class _AppAuth'));
        expect(code, contains('class _AppAuthLogin'));
      });
    });

    group('Delegate Generation', () {
      test('generates delegate class', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains('class TestLocalizationsDelegate'));
        expect(code, contains('extends LocalizationsDelegate'));
      });

      test('generates load method', () {
        final locales = [LocaleData(locale: 'en', items: {})];
        final code = writer.generate(locales);

        expect(code, contains('Future<TestLocalizations> load'));
      });
    });

    group('Dartdoc Metadata', () {
      test(
          'does not emit per-key metadata into generated output (currently skipped)',
          () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'welcome_user': LocalizationItem(
                key: 'welcome_user',
                value: 'Welcome, {name}.',
                parameters: ['name'],
                description: 'Greets a user by name.',
                example: 'Welcome, John.',
                placeholderDocs: const {
                  'name': 'User display name',
                },
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        // Should still generate the API.
        expect(code, contains('String welcomeUser({required String name})'));

        // But should not embed metadata text into dartdoc yet.
        expect(code, isNot(contains('Greets a user by name.')));
        expect(code, isNot(contains('Placeholders:')));
        expect(code, isNot(contains('User display name')));
        expect(code, isNot(contains('Welcome, John.')));
      });
    });

    group('Field Rename', () {
      test('applies fieldRename to simple keys (camelCase)', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'first_name': LocalizationItem(
                key: 'first_name',
                value: 'First Name',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String get firstName'));
      });

      test('applies fieldRename to nested keys (camelCase)', () {
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'user_profile.first_name': LocalizationItem(
                key: 'user_profile.first_name',
                value: 'First Name',
                parameters: [],
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('get userProfile'));
        expect(code, contains('String get firstName'));
      });
    });

    group('Runtime key resolver', () {
      test('generates resolveByKey with namespace and fallback', () {
        final writer = DartWriter(className: 'TestLocalizations');
        final locales = [
          LocaleData(
            locale: 'en',
            items: {
              'app.title': LocalizationItem(
                key: 'app.title',
                value: 'Demo',
              ),
            },
          ),
          LocaleData(
            locale: 'id',
            items: {
              'app.title': LocalizationItem(
                key: 'app.title',
                value: 'Demo',
              ),
            },
          ),
        ];

        final code = writer.generate(locales);

        expect(code, contains('String? resolveByKey('));
        expect(code, contains('String? namespace'));
        expect(code, contains('String? fallback'));

        // Preferred direct-call usage style in docs (must match exactly)
        expect(
          code,
          contains("TestLocalizations.of(context).resolveByKey('app.title');"),
        );

        // Implementation
        expect(code, contains("? key.trim()"));
        expect(code, contains(r": '${namespace.trim()}.${key.trim()}';"));
        expect(code,
            contains('return _activeTranslations[normalizedKey] ?? fallback;'));

        // No per-case const maps anymore.
        expect(code, isNot(contains('const map = <String, String>{')));
      });
    });

    // Add an assertion ensuring the top-level dartdoc usage example matches namespaced access
    test('class dartdoc usage example uses namespaced access', () {
      final locales = [
        LocaleData(locale: 'en', items: {
          'simple.hello': LocalizationItem(key: 'simple.hello', value: 'Hello')
        })
      ];
      final code = writer.generate(locales);
      expect(code, contains('final text = appLocalizations.simple.hello;'));
    });
  });
}
