import 'dart:convert';

import 'package:localization_gen/src/model/field_rename.dart';
import 'package:localization_gen/src/model/localization_item.dart';

/// Generates strongly-typed Dart code with nested structure support.
///
/// This class is responsible for converting parsed localization data into
/// Dart code with type-safe access to translations. It supports nested JSON
/// structures, parameter interpolation, pluralization, gender forms, and
/// context-based translations.
///
/// The generated code follows Flutter's localization patterns and provides
/// compile-time checking of translation keys.
///
/// Example usage:
/// ```dart
/// final writer = DartWriter(
///   className: 'AppLocalizations',
/// );
/// final dartCode = writer.generate(locales);
/// ```
class DartWriter {
  /// The name of the generated localization class.
  ///
  /// This will be the class name used in your Flutter application,
  /// typically 'AppLocalizations'. The generated code can be accessed as:
  /// ```dart
  /// final appLocalizations = AppLocalizations.of(context);
  /// ```
  final String className;

  /// Controls how JSON key segments are converted into Dart identifiers.
  final FieldRename fieldRename;

  /// Creates a new DartWriter instance.
  ///
  /// The [className] parameter specifies the name of the generated class
  /// (typically 'AppLocalizations').
  ///
  /// The [fieldRename] parameter controls identifier naming. It defaults to
  /// [FieldRename.camel].
  DartWriter({
    required this.className,
    this.fieldRename = FieldRename.camel,
  });

  /// Generates complete Dart file content from locale data.
  ///
  /// This method orchestrates the generation of a complete Dart localization
  /// file including imports, class definitions, nested classes, methods,
  /// and the localization delegate.
  ///
  /// The [locales] parameter contains all parsed locale data. The first locale
  /// in the list is used as the base locale for structure determination.
  ///
  /// Returns a string containing the complete Dart source code ready to be
  /// written to a file.
  ///
  /// Throws [Exception] if the locales list is empty.
  ///
  /// Example:
  /// ```dart
  /// final dartCode = writer.generate([
  ///   LocaleData(locale: 'en', items: {...}),
  ///   LocaleData(locale: 'es', items: {...}),
  /// ]);
  /// ```
  String generate(List<LocaleData> locales) {
    if (locales.isEmpty) throw Exception('No locales to generate');

    final baseLocale = locales.first;
    final fallbackLocaleCode = baseLocale.locale;
    final buffer = StringBuffer();

    // Header & imports
    buffer.writeln("// GENERATED CODE - DO NOT MODIFY BY HAND");
    buffer.writeln("// Generated by localization_gen");
    buffer.writeln();
    buffer.writeln("import 'package:flutter/widgets.dart';");
    buffer.writeln();

    // Main class
    buffer.writeln(
        "/// Strongly-typed localization class for application translations.");
    buffer.writeln("///");
    buffer.writeln("/// Access translations using:");
    buffer.writeln("/// ```dart");
    buffer.writeln("/// final appLocalizations = $className.of(context);");
    buffer.writeln("/// final text = appLocalizations.simple.hello;");
    buffer.writeln("/// ```");
    buffer.writeln("class $className {");
    buffer.writeln(
        "  /// Creates a new $className instance for the specified locale.");
    buffer.writeln("  $className(this.locale);");
    buffer.writeln();
    buffer.writeln("  /// The locale for this localization instance.");
    buffer.writeln("  final Locale locale;");
    buffer.writeln();

    // Static of() method (mandatory)
    buffer.writeln("  /// Gets the localization instance from BuildContext.");
    buffer.writeln("  ///");
    buffer.writeln("  /// Example:");
    buffer.writeln("  /// ```dart");
    buffer.writeln("  /// final appLocalizations = $className.of(context);");
    buffer.writeln("  /// ```");
    buffer.writeln("  static $className of(BuildContext context) {");
    buffer.writeln(
        "    return Localizations.of<$className>(context, $className)!;");
    buffer.writeln("  }");
    buffer.writeln();

    // Supported locales
    buffer.writeln("  /// All supported locales for this application.");
    buffer.writeln("  static const supportedLocales = [");
    for (final locale in locales) {
      buffer.writeln("    Locale('${locale.locale}'),");
    }
    buffer.writeln("  ];");
    buffer.writeln();

    // Translation tables (dictionary-first)
    buffer.writeln('  /// Translation tables (per locale).');
    buffer.writeln('  ///');
    buffer.writeln('  /// Notes');
    buffer.writeln(
        '  /// - Tables are generated once to avoid per-getter locale switching.');
    buffer.writeln(
        '  /// - Missing locale translations return null / empty maps (no fallback).');
    buffer.writeln(
        "  static const String _fallbackLocale = '$fallbackLocaleCode';");

    // Build special-form tables (plural/gender/context)
    final pluralKeys = baseLocale.items.values
        .where((i) => i.hasPlurals)
        .map((i) => i.key)
        .toSet();
    final genderKeys = baseLocale.items.values
        .where((i) => i.hasGenders)
        .map((i) => i.key)
        .toSet();
    final contextKeys = baseLocale.items.values
        .where((i) => i.hasContexts)
        .map((i) => i.key)
        .toSet();

    for (final locale in locales) {
      final entries = locale.items.entries.toList()
        ..sort((a, b) => a.key.compareTo(b.key));

      buffer.writeln(
          "  static const Map<String, String> _t_${locale.locale} = {");
      for (final entry in entries) {
        // Only plain strings (including templates with {placeholders}).
        buffer.writeln(
            '    ${jsonEncode(entry.key)}: ${_dartStringLiteral(entry.value.value)},');
      }
      buffer.writeln('  };');

      // Plural forms
      if (pluralKeys.isNotEmpty) {
        buffer.writeln(
            "  static const Map<String, Map<String, String>> _p_${locale.locale} = {");
        final keys = pluralKeys.toList()..sort();
        for (final k in keys) {
          final item = locale.items[k];
          final forms = item?.pluralForms;
          if (forms == null || forms.isEmpty) continue;
          buffer.writeln('    ${jsonEncode(k)}: {');
          final formEntries = forms.entries.toList()
            ..sort((a, b) => a.key.compareTo(b.key));
          for (final e in formEntries) {
            buffer.writeln("      '${e.key}': ${_dartStringLiteral(e.value)},");
          }
          buffer.writeln('    },');
        }
        buffer.writeln('  };');
      }

      // Gender forms
      if (genderKeys.isNotEmpty) {
        buffer.writeln(
            "  static const Map<String, Map<String, String>> _g_${locale.locale} = {");
        final keys = genderKeys.toList()..sort();
        for (final k in keys) {
          final item = locale.items[k];
          final forms = item?.genderForms;
          if (forms == null || forms.isEmpty) continue;
          buffer.writeln('    ${jsonEncode(k)}: {');
          final formEntries = forms.entries.toList()
            ..sort((a, b) => a.key.compareTo(b.key));
          for (final e in formEntries) {
            buffer.writeln("      '${e.key}': ${_dartStringLiteral(e.value)},");
          }
          buffer.writeln('    },');
        }
        buffer.writeln('  };');
      }

      // Context forms
      if (contextKeys.isNotEmpty) {
        buffer.writeln(
            "  static const Map<String, Map<String, String>> _c_${locale.locale} = {");
        final keys = contextKeys.toList()..sort();
        for (final k in keys) {
          final item = locale.items[k];
          final forms = item?.contextForms;
          if (forms == null || forms.isEmpty) continue;
          buffer.writeln('    ${jsonEncode(k)}: {');
          final formEntries = forms.entries.toList()
            ..sort((a, b) => a.key.compareTo(b.key));
          for (final e in formEntries) {
            buffer.writeln("      '${e.key}': ${_dartStringLiteral(e.value)},");
          }
          buffer.writeln('    },');
        }
        buffer.writeln('  };');
      }
    }

    buffer.writeln(
        '  static const Map<String, Map<String, String>> _translations = {');
    for (final locale in locales) {
      buffer.writeln("    '${locale.locale}': _t_${locale.locale},");
    }
    buffer.writeln('  };');

    if (pluralKeys.isNotEmpty) {
      buffer.writeln(
          '  static const Map<String, Map<String, Map<String, String>>> _plurals = {');
      for (final locale in locales) {
        buffer.writeln("    '${locale.locale}': _p_${locale.locale},");
      }
      buffer.writeln('  };');
    }

    if (genderKeys.isNotEmpty) {
      buffer.writeln(
          '  static const Map<String, Map<String, Map<String, String>>> _genders = {');
      for (final locale in locales) {
        buffer.writeln("    '${locale.locale}': _g_${locale.locale},");
      }
      buffer.writeln('  };');
    }

    if (contextKeys.isNotEmpty) {
      buffer.writeln(
          '  static const Map<String, Map<String, Map<String, String>>> _contexts = {');
      for (final locale in locales) {
        buffer.writeln("    '${locale.locale}': _c_${locale.locale},");
      }
      buffer.writeln('  };');
    }

    buffer.writeln();

    buffer.writeln('  Map<String, String> get _activeTranslations {');
    buffer.writeln('    return _translations[locale.languageCode] ?? const <String, String>{};');
    buffer.writeln('  }');
    buffer.writeln();

    if (pluralKeys.isNotEmpty) {
      buffer.writeln('  Map<String, Map<String, String>> get _activePlurals {');
      buffer.writeln('    return _plurals[locale.languageCode] ?? const <String, Map<String, String>>{};');
      buffer.writeln('  }');
      buffer.writeln();
    }

    if (genderKeys.isNotEmpty) {
      buffer.writeln('  Map<String, Map<String, String>> get _activeGenders {');
      buffer.writeln('    return _genders[locale.languageCode] ?? const <String, Map<String, String>>{};');
      buffer.writeln('  }');
      buffer.writeln();
    }

    if (contextKeys.isNotEmpty) {
      buffer.writeln('  Map<String, Map<String, String>> get _activeContexts {');
      buffer.writeln('    return _contexts[locale.languageCode] ?? const <String, Map<String, String>>{};');
      buffer.writeln('  }');
      buffer.writeln();
    }

    // Shared lookup helpers
    buffer.writeln('  String? _t(String key) {');
    buffer.writeln('    return _activeTranslations[key];');
    buffer.writeln('  }');
    buffer.writeln();

    // Runtime resolver (optional namespace)
    buffer.writeln(
        '  /// Resolves a translation by its **flattened key path** at runtime.');
    buffer.writeln('  ///');
    buffer.writeln('  /// Summary');
    buffer.writeln(
        '  /// - Useful for dynamic lookups (e.g. received keys from backend).');
    buffer.writeln(
        '  /// - Supports an optional [namespace] prefix to reduce repetition.');
    buffer.writeln('  /// - Returns null if the key is missing for the current locale.');
    buffer.writeln('  ///');
    buffer.writeln('  /// Usage');
    buffer.writeln('  /// ```dart');
    buffer.writeln("  /// $className.of(context).resolveByKey('app.title');");
    buffer.writeln(
        "  /// $className.of(context).resolveByKey('title', namespace: 'app');");
    buffer.writeln('  /// ```');
    buffer.writeln('  ///');
    buffer.writeln('  /// Notes');
    buffer.writeln(
        '  /// - This does not do placeholder interpolation. For placeholders, prefer the typed API.');
    buffer.writeln('  String? resolveByKey(');
    buffer.writeln('    String key, {');
    buffer.writeln('    String? namespace,');
    buffer.writeln('  }) {');
    buffer.writeln(
        '    final normalizedKey = (namespace == null || namespace.trim().isEmpty)');
    buffer.writeln('        ? key.trim()');
    buffer.writeln(r"        : '${namespace.trim()}.${key.trim()}';");
    buffer.writeln();
    buffer.writeln('    return _activeTranslations[normalizedKey];');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln(
        '  String _format(String template, Map<String, String> params) {');
    buffer.writeln('    // Supports {token} placeholders.');
    buffer.writeln('    // Use double braces to escape literals: {{ and }}');
    buffer.writeln("    var out = template.replaceAll('{{', '\\u0000');");
    buffer.writeln("    out = out.replaceAll('}}', '\\u0001');");
    buffer.writeln('    params.forEach((k, v) {');
    buffer.writeln("      out = out.replaceAll('{' + k + '}', v);");
    buffer.writeln('    });');
    buffer.writeln("    out = out.replaceAll('\\u0000', '{');");
    buffer.writeln("    out = out.replaceAll('\\u0001', '}');");
    buffer.writeln('    return out;');
    buffer.writeln('  }');

    buffer.writeln(
        '  String? _tf(String key, Map<String, String> params) {');
    buffer.writeln('    final template = _t(key);');
    buffer.writeln('    if (template == null) return null;');
    buffer.writeln('    return _format(template, params);');
    buffer.writeln('  }');
    buffer.writeln();

    // Helper methods if any locale has plurals, genders, or contexts
    final hasAnySpecialForms = baseLocale.items.values
        .any((item) => item.hasPlurals || item.hasGenders || item.hasContexts);
    if (hasAnySpecialForms) {
      buffer.writeln(_generateHelperMethods());
    }

    buffer.writeln();

    // Build nested structure
    final nestedStructure = _buildNestedStructure(baseLocale.items);

    // Generate nested class getters
    for (final entry in nestedStructure.entries) {
      final key = entry.key;
      final value = entry.value;

      if (value is Map) {
        // This is a namespace, create a getter for nested class
        final nestedClassName = '_${_toPascalCase(_renameSegment(key))}';
        buffer.writeln("  /// Translations for the $key namespace.");
        buffer.writeln(
            "  $nestedClassName get ${_renameSegment(key)} => $nestedClassName(this);");
        buffer.writeln();
      }
    }

    // Generate methods for top-level keys
    for (final entry in baseLocale.items.entries) {
      final item = entry.value;
      if (!item.key.contains('.')) {
        buffer.writeln(_generateMethod(item, locales));
      }
    }

    buffer.writeln("}");
    buffer.writeln();

    // Generate nested classes
    buffer.write(
        _generateNestedClasses(nestedStructure, locales, baseLocale.items));

    // Generate delegate
    buffer.writeln(_generateDelegate(locales));

    return buffer.toString();
  }

  /// Builds a nested structure from flat dot-notation keys.
  ///
  /// This method converts a flat map of localization items with dot-notation
  /// keys into a hierarchical nested map structure suitable for code generation.
  ///
  /// The [items] parameter contains the flat map of localization items.
  ///
  /// Returns a nested map where each level represents a namespace.
  ///
  /// Example transformation:
  /// ```dart
  /// // Input:
  /// {"auth.login.title": "Login"}
  ///
  /// // Output:
  /// {"auth": {"login": {"title": LocalizationItem(...)}}}
  /// ```
  Map<String, dynamic> _buildNestedStructure(
      Map<String, LocalizationItem> items) {
    final result = <String, dynamic>{};

    for (final item in items.values) {
      final parts = item.key.split('.');
      if (parts.length == 1) continue; // Skip top-level keys

      var current = result;
      for (var i = 0; i < parts.length - 1; i++) {
        current.putIfAbsent(parts[i], () => <String, dynamic>{});
        current = current[parts[i]] as Map<String, dynamic>;
      }
      current[parts.last] = item;
    }

    return result;
  }

  /// Generates nested classes for namespaces with full recursive support.
  ///
  /// This method creates Dart class definitions for each namespace level in
  /// the nested translation structure. Each nested class provides type-safe
  /// access to its translations.
  ///
  /// The [structure] parameter contains the nested map of translations.
  /// The [locales] parameter contains all locale data for generating switches.
  /// The [allItems] parameter contains all flat localization items for reference.
  ///
  /// Returns a string containing the generated nested class definitions.
  ///
  /// Example generated code:
  /// ```dart
  /// class _Auth {
  ///   _Auth(this.locale);
  ///   final Locale locale;
  ///   _AuthLogin get login => _AuthLogin(locale);
  /// }
  /// ```
  String _generateNestedClasses(
    Map<String, dynamic> structure,
    List<LocaleData> locales,
    Map<String, LocalizationItem> allItems,
  ) {
    final buffer = StringBuffer();
    _generateNestedClassesRecursive(structure, locales, '', buffer);
    return buffer.toString();
  }

  /// Recursively generates nested classes for any depth level.
  ///
  /// This method is called recursively to generate class definitions for
  /// deeply nested translation structures, supporting up to 10 levels deep.
  ///
  /// The [structure] parameter contains the current level's nested map.
  /// The [locales] parameter contains all locale data.
  /// The [parentPath] parameter tracks the current path for class naming.
  /// The [buffer] parameter accumulates the generated code.
  ///
  /// Each generated class includes:
  /// - A constructor accepting a Locale
  /// - Getters for sub-namespaces
  /// - Methods for leaf translation nodes
  void _generateNestedClassesRecursive(
    Map<String, dynamic> structure,
    List<LocaleData> locales,
    String parentPath,
    StringBuffer buffer,
  ) {
    for (final entry in structure.entries) {
      final key = entry.key;
      final value = entry.value;

      if (value is Map) {
        // Build class name from parent path
        final currentPath = parentPath.isEmpty ? key : '${parentPath}_$key';
        final className =
            '_${_pathToPascalCase(_renameUnderscorePath(currentPath))}';
        final displayPath = currentPath.replaceAll('_', '.');

        buffer.writeln("/// Translations for $displayPath namespace");
        buffer.writeln("class $className {");
        buffer.writeln("  $className(this._root);");
        buffer.writeln();
        buffer.writeln("  final ${this.className} _root;");
        buffer.writeln("  Locale get locale => _root.locale;");
        buffer.writeln();

        // Convert to Map<String, dynamic> for type safety
        final valueMap = Map<String, dynamic>.from(value);

        // Generate nested class getters for sub-namespaces
        for (final nestedEntry in valueMap.entries) {
          final nestedKey = nestedEntry.key;
          final nestedValue = nestedEntry.value;

          if (nestedValue is Map) {
            final nestedPath = '${currentPath}_$nestedKey';
            final nestedClassName =
                '_${_pathToPascalCase(_renameUnderscorePath(nestedPath))}';
            final renamedNestedKey = _renameSegment(nestedKey);
            buffer.writeln("  /// App $displayPath.$nestedKey translations");
            buffer.writeln(
                "  $nestedClassName get $renamedNestedKey => $nestedClassName(_root);");
            buffer.writeln();
          }
        }

        // Generate methods for leaf nodes in this namespace
        for (final nestedEntry in valueMap.entries) {
          if (nestedEntry.value is LocalizationItem) {
            buffer.writeln(_generateMethod(
              nestedEntry.value as LocalizationItem,
              locales,
              isNested: true,
            ));
          }
        }

        buffer.writeln("}");
        buffer.writeln();

        // Recursively generate nested classes for deeper levels
        _generateNestedClassesRecursive(valueMap, locales, currentPath, buffer);
      }
    }
  }

  /// Generates a single method for a localization key.
  ///
  /// This method creates either a getter or a method with parameters for
  /// accessing a specific translation. It handles parameter interpolation,
  /// pluralization, gender forms, and context forms.
  ///
  /// The [item] parameter contains the localization item data.
  /// The [locales] parameter contains all locale data for generating switches.
  /// The [isNested] parameter indicates if this is in a nested class.
  ///
  /// Returns a string containing the generated method code.
  ///
  /// Example generated code for a simple getter:
  /// ```dart
  /// String get hello {
  ///   switch (locale.languageCode) {
  ///     case 'en': return 'Hello';
  ///     default: return 'Hello';
  ///   }
  /// }
  /// ```
  ///
  /// Example generated code for a parameterized method:
  /// ```dart
  /// String welcome({required String name}) {
  ///   switch (locale.languageCode) {
  ///     case 'en': return 'Welcome $name';
  ///     default: return 'Welcome $name';
  ///   }
  /// }
  /// ```
  String _generateMethod(LocalizationItem item, List<LocaleData> locales,
      {bool isNested = false}) {
    final buffer = StringBuffer();

    final simpleKey = item.key.split('.').last;
    final methodName = _renameSegment(simpleKey);

    // Handle pluralization
    if (item.hasPlurals) {
      return _generatePluralMethod(item, locales, methodName);
    }

    // Handle gender forms
    if (item.hasGenders) {
      return _generateGenderMethod(item, locales, methodName);
    }

    // Handle context forms
    if (item.hasContexts) {
      return _generateContextMethod(item, locales, methodName);
    }

    if (item.hasParameters) {
      final placeholderMap = _buildPlaceholderMap(item.parameters);
      final signatureParams = placeholderMap.values.toList(growable: false);

      final params =
          signatureParams.map((p) => 'required String $p').join(', ');
      buffer.writeln("  String? $methodName({$params}) {");

      final paramsMap = item.parameters.map((p) {
        final dartName = placeholderMap[p] ?? _renameSegment(p);
        return "'$p': $dartName";
      }).join(', ');

      if (isNested) {
        buffer.writeln(
            "    return _root._tf(${jsonEncode(item.key)}, {$paramsMap});");
      } else {
        buffer.writeln(
            "    return this._tf(${jsonEncode(item.key)}, {$paramsMap});");
      }
      buffer.writeln("  }");
    } else {
      buffer.writeln("  String? get $methodName {");
      if (isNested) {
        buffer.writeln("    return _root._t(${jsonEncode(item.key)});");
      } else {
        buffer.writeln("    return this._t(${jsonEncode(item.key)});");
      }
      buffer.writeln("  }");
    }

    buffer.writeln();
    return buffer.toString();
  }

  /// Produces a Dart string literal that is always syntactically valid.
  ///
  /// This generator uses double-quoted Dart string literals.
  /// It escapes:
  /// - backslashes
  /// - control characters (\r, \n, \t)
  /// - dollar signs (to prevent interpolation)
  /// - double quotes
  String _dartStringLiteral(String text) {
    // jsonEncode gives us a valid JSON string in double quotes with escapes.
    // Example: Hello -> "Hello"
    var encoded = jsonEncode(text);

    // Escape '$' for Dart string literals (avoid accidental interpolation).
    // We are generating Dart *source* here. We must emit exactly `\$`.
    encoded = encoded.replaceAll(r'$', r'\$');

    // Strip surrounding JSON quotes.
    final inner = encoded.substring(1, encoded.length - 1);

    // Wrap with Dart double quotes. At this point, inner already contains
    // the needed escapes for backslashes/control chars/double quotes.
    return '"$inner"';
  }

  /// Builds a stable mapping from JSON placeholder token name -> Dart identifier.
  ///
  /// Example:
  /// - JSON placeholder: `first_name`
  /// - Dart identifier (camel): `firstName`
  Map<String, String> _buildPlaceholderMap(List<String> placeholders) {
    final map = <String, String>{};
    for (final p in placeholders) {
      map[p] = _renameSegment(p);
    }
    return map;
  }

  /// Generates a method for pluralization support.
  ///
  /// Creates a method that selects the appropriate plural form based on count.
  /// Supports forms: zero, one, two, few, many, other.
  ///
  /// The [item] parameter contains the localization item with plural forms.
  /// The [locales] parameter contains all locale data.
  /// The [simpleKey] parameter is the method name to generate.
  ///
  /// Returns a string containing the generated pluralization method.
  String _generatePluralMethod(
      LocalizationItem item, List<LocaleData> locales, String simpleKey) {
    final buffer = StringBuffer();

    final placeholderMap = _buildPlaceholderMap(item.parameters);

    final extraParams = item.parameters
        .where((p) => p != 'count')
        .map((p) => placeholderMap[p] ?? _renameSegment(p))
        .toList(growable: false);

    final paramStr = extraParams.isEmpty
        ? '{required int count}'
        : '{required int count, ${extraParams.map((p) => 'required String $p').join(', ')}}';

    final paramsMapEntries = <String>['\'count\': count.toString()'];
    for (final p in item.parameters.where((p) => p != 'count')) {
      final dartName = placeholderMap[p] ?? _renameSegment(p);
      paramsMapEntries.add("'$p': $dartName");
    }

    buffer.writeln("  String? $simpleKey($paramStr) {");
    buffer.writeln(
        "    final forms = _activePlurals[${jsonEncode(item.key)}] ?? const <String, String>{};");
    buffer.writeln("    final template = _selectPlural(count, forms);");
    buffer.writeln(
        "    return _format(template, {${paramsMapEntries.join(', ')}});");
    buffer.writeln("  }");
    buffer.writeln();
    return buffer.toString();
  }

  /// Generates a method for gender-based forms.
  ///
  /// Creates a method that selects the appropriate form based on gender.
  /// Supports forms: male, female, other.
  ///
  /// The [item] parameter contains the localization item with gender forms.
  /// The [locales] parameter contains all locale data.
  /// The [simpleKey] parameter is the method name to generate.
  ///
  /// Returns a string containing the generated gender-based method.
  String _generateGenderMethod(
      LocalizationItem item, List<LocaleData> locales, String simpleKey) {
    final buffer = StringBuffer();

    final placeholderMap = _buildPlaceholderMap(item.parameters);

    final extraParams = item.parameters
        .where((p) => p != 'gender')
        .map((p) => placeholderMap[p] ?? _renameSegment(p))
        .toList(growable: false);

    final paramStr = extraParams.isEmpty
        ? '{required String gender}'
        : '{required String gender, ${extraParams.map((p) => 'required String $p').join(', ')}}';

    final paramsMapEntries = <String>[];
    for (final p in item.parameters.where((p) => p != 'gender')) {
      final dartName = placeholderMap[p] ?? _renameSegment(p);
      paramsMapEntries.add("'$p': $dartName");
    }

    buffer.writeln("  String? $simpleKey($paramStr) {");
    buffer.writeln(
        "    final forms = _activeGenders[${jsonEncode(item.key)}] ?? const <String, String>{};");
    buffer.writeln("    final template = _selectGender(gender, forms);");
    buffer.writeln(
        "    return _format(template, {${paramsMapEntries.join(', ')}});");
    buffer.writeln("  }");
    buffer.writeln();
    return buffer.toString();
  }

  /// Generates a method for context-based forms.
  ///
  /// Creates a method that selects the appropriate form based on context.
  /// The context parameter allows translations to vary based on usage context.
  ///
  /// The [item] parameter contains the localization item with context forms.
  /// The [locales] parameter contains all locale data.
  /// The [simpleKey] parameter is the method name to generate.
  ///
  /// Returns a string containing the generated context-based method.
  String _generateContextMethod(
      LocalizationItem item, List<LocaleData> locales, String simpleKey) {
    final buffer = StringBuffer();

    final placeholderMap = _buildPlaceholderMap(item.parameters);

    final extraParams = item.parameters
        .where((p) => p != 'context')
        .map((p) => placeholderMap[p] ?? _renameSegment(p))
        .toList(growable: false);

    final paramStr = extraParams.isEmpty
        ? '{required String context}'
        : '{required String context, ${extraParams.map((p) => 'required String $p').join(', ')}}';

    final paramsMapEntries = <String>[];
    for (final p in item.parameters.where((p) => p != 'context')) {
      final dartName = placeholderMap[p] ?? _renameSegment(p);
      paramsMapEntries.add("'$p': $dartName");
    }

    buffer.writeln("  String? $simpleKey($paramStr) {");
    buffer.writeln(
        "    final forms = _activeContexts[${jsonEncode(item.key)}] ?? const <String, String>{};");
    buffer.writeln("    final template = _selectContext(context, forms);");
    buffer.writeln(
        "    return _format(template, {${paramsMapEntries.join(', ')}});");
    buffer.writeln("  }");
    buffer.writeln();
    return buffer.toString();
  }

  // Helpers for renaming
  String _renameSegment(String segment) {
    // Preserve already-valid identifiers when mode is none.
    // For other modes, rely on FieldRename.convert.
    return fieldRename.convert(segment);
  }

  String _renameUnderscorePath(String underscorePath) {
    // Used for class names built from underscore paths.
    // Convert each underscore-separated segment then rejoin with underscores
    // so existing PascalCase builders can still work.
    return underscorePath.split('_').map(_renameSegment).join('_');
  }

  /// Converts a string to PascalCase.
  ///
  /// Used for generating class names from namespace keys.
  ///
  /// Example:
  /// ```dart
  /// _toPascalCase('hello_world'); // Returns 'HelloWorld'
  /// ```
  String _toPascalCase(String input) => input.split('_').map((part) {
        if (part.isEmpty) return '';
        return part[0].toUpperCase() + part.substring(1);
      }).join();

  /// Converts a path to PascalCase for class names.
  ///
  /// Handles underscores in nested paths to create appropriate class names.
  String _pathToPascalCase(String path) {
    return path.split('_').map((part) {
      if (part.isEmpty) return '';
      return part[0].toUpperCase() + part.substring(1);
    }).join('');
  }

  /// Generates helper methods for plural, gender, and context selection.
  ///
  /// These helper methods are used by generated translation methods to select
  /// the appropriate form based on count, gender, or context parameters.
  ///
  /// Returns a string containing the helper method implementations:
  /// - `_selectPlural`: Selects plural form based on count
  /// - `_selectGender`: Selects gender form based on gender parameter
  /// - `_selectContext`: Selects context form based on context parameter
  String _generateHelperMethods() {
    return '''
  /// Select the appropriate plural form based on count
  String _selectPlural(int count, Map<String, String> forms) {
    if (count == 0 && forms.containsKey('zero')) return forms['zero']!;
    if (count == 1 && forms.containsKey('one')) return forms['one']!;
    if (count == 2 && forms.containsKey('two')) return forms['two']!;
    if (forms.containsKey('many') && count >= 5) return forms['many']!;
    if (forms.containsKey('few') && count >= 2 && count <= 4) return forms['few']!;
    return forms['other'] ?? forms.values.first;
  }

  /// Select the appropriate gender form
  String _selectGender(String gender, Map<String, String> forms) {
    return forms[gender.toLowerCase()] ?? forms['other'] ?? forms.values.first;
  }

  /// Select the appropriate context form
  String _selectContext(String context, Map<String, String> forms) {
    return forms[context.toLowerCase()] ?? forms.values.first;
  }
''';
  }

  /// Generates the LocalizationsDelegate implementation.
  ///
  /// Creates a delegate class that Flutter uses to load localization instances.
  /// Also generates an extension for convenient access.
  ///
  /// The [locales] parameter contains all supported locale data.
  ///
  /// Returns a string containing the delegate class and extension code.
  ///
  /// Generated code includes:
  /// - `isSupported`: Checks if a locale is supported
  /// - `load`: Loads localization instance for a locale
  /// - `shouldReload`: Controls when to reload (always false)
  /// - Extension with static delegate accessor
  String _generateDelegate(List<LocaleData> locales) {
    final buffer = StringBuffer();

    buffer.writeln("/// Localization delegate for $className");
    buffer.writeln(
        "class ${className}Delegate extends LocalizationsDelegate<$className> {");
    buffer.writeln("  const ${className}Delegate();");
    buffer.writeln();
    buffer.writeln("  @override");
    buffer.writeln("  bool isSupported(Locale locale) {");
    buffer.writeln("    return $className.supportedLocales");
    buffer.writeln("        .map((l) => l.languageCode)");
    buffer.writeln("        .contains(locale.languageCode);");
    buffer.writeln("  }");
    buffer.writeln();
    buffer.writeln("  @override");
    buffer.writeln("  Future<$className> load(Locale locale) async {");
    buffer.writeln("    return $className(locale);");
    buffer.writeln("  }");
    buffer.writeln();
    buffer.writeln("  @override");
    buffer.writeln("  bool shouldReload(${className}Delegate old) => false;");
    buffer.writeln("}");
    buffer.writeln();
    buffer.writeln("/// Extension for easy access");
    buffer.writeln("extension ${className}Extension on $className {");
    buffer.writeln('  static const delegate = ${className}Delegate();');
    buffer.writeln('}');

    return buffer.toString();
  }
}
