// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by localization_gen

import 'package:flutter/widgets.dart';

/// Strongly-typed localization class
class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  /// Get the localization instance from context
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  /// All supported locales
  static const supportedLocales = [Locale('en'), Locale('id'), Locale('es')];

  /// App common translations
  _Common get common => _Common(locale);

  /// App auth translations
  _Auth get auth => _Auth(locale);

  /// App home translations
  _Home get home => _Home(locale);

  /// App settings translations
  _Settings get settings => _Settings(locale);

  /// App app translations
  _App get app => _App(locale);
}

/// Translations for common namespace
class _Common {
  _Common(this.locale);

  final Locale locale;

  String get hello {
    switch (locale.languageCode) {
      case 'en':
        return 'Hello';
      case 'id':
        return 'Halo';
      case 'es':
        return 'Hola';
      default:
        return 'Hello';
    }
  }

  String get goodbye {
    switch (locale.languageCode) {
      case 'en':
        return 'Goodbye';
      case 'id':
        return 'Selamat tinggal';
      case 'es':
        return 'Adiós';
      default:
        return 'Goodbye';
    }
  }

  String get yes {
    switch (locale.languageCode) {
      case 'en':
        return 'Yes';
      case 'id':
        return 'Ya';
      case 'es':
        return 'Sí';
      default:
        return 'Yes';
    }
  }

  String get no {
    switch (locale.languageCode) {
      case 'en':
        return 'No';
      case 'id':
        return 'Tidak';
      case 'es':
        return 'No';
      default:
        return 'No';
    }
  }

  String get save {
    switch (locale.languageCode) {
      case 'en':
        return 'Save';
      case 'id':
        return 'Simpan';
      case 'es':
        return 'Guardar';
      default:
        return 'Save';
    }
  }

  String get cancel {
    switch (locale.languageCode) {
      case 'en':
        return 'Cancel';
      case 'id':
        return 'Batal';
      case 'es':
        return 'Cancelar';
      default:
        return 'Cancel';
    }
  }
}

/// Translations for auth namespace
class _Auth {
  _Auth(this.locale);

  final Locale locale;

  /// App auth.login translations
  _AuthLogin get login => _AuthLogin(locale);

  /// App auth.register translations
  _AuthRegister get register => _AuthRegister(locale);

  /// App auth.errors translations
  _AuthErrors get errors => _AuthErrors(locale);
}

/// Translations for auth.login namespace
class _AuthLogin {
  _AuthLogin(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Login';
      case 'id':
        return 'Masuk';
      case 'es':
        return 'Iniciar Sesión';
      default:
        return 'Login';
    }
  }

  String get email {
    switch (locale.languageCode) {
      case 'en':
        return 'Email';
      case 'id':
        return 'Email';
      case 'es':
        return 'Correo Electrónico';
      default:
        return 'Email';
    }
  }

  String get password {
    switch (locale.languageCode) {
      case 'en':
        return 'Password';
      case 'id':
        return 'Kata Sandi';
      case 'es':
        return 'Contraseña';
      default:
        return 'Password';
    }
  }

  String get button {
    switch (locale.languageCode) {
      case 'en':
        return 'Sign In';
      case 'id':
        return 'Masuk';
      case 'es':
        return 'Entrar';
      default:
        return 'Sign In';
    }
  }

  String get forgot_password {
    switch (locale.languageCode) {
      case 'en':
        return 'Forgot Password?';
      case 'id':
        return 'Lupa Kata Sandi?';
      case 'es':
        return '¿Olvidaste tu contraseña?';
      default:
        return 'Forgot Password?';
    }
  }
}

/// Translations for auth.register namespace
class _AuthRegister {
  _AuthRegister(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Register';
      case 'id':
        return 'Daftar';
      case 'es':
        return 'Registrarse';
      default:
        return 'Register';
    }
  }

  String get button {
    switch (locale.languageCode) {
      case 'en':
        return 'Sign Up';
      case 'id':
        return 'Buat Akun';
      case 'es':
        return 'Crear Cuenta';
      default:
        return 'Sign Up';
    }
  }

  String get terms_accept {
    switch (locale.languageCode) {
      case 'en':
        return 'I accept the terms and conditions';
      case 'id':
        return 'Saya menerima syarat dan ketentuan';
      case 'es':
        return 'Acepto los términos y condiciones';
      default:
        return 'I accept the terms and conditions';
    }
  }
}

/// Translations for auth.errors namespace
class _AuthErrors {
  _AuthErrors(this.locale);

  final Locale locale;

  String get invalid_email {
    switch (locale.languageCode) {
      case 'en':
        return 'Invalid email address';
      case 'id':
        return 'Alamat email tidak valid';
      case 'es':
        return 'Correo electrónico inválido';
      default:
        return 'Invalid email address';
    }
  }

  String get weak_password {
    switch (locale.languageCode) {
      case 'en':
        return 'Password is too weak';
      case 'id':
        return 'Kata sandi terlalu lemah';
      case 'es':
        return 'La contraseña es muy débil';
      default:
        return 'Password is too weak';
    }
  }

  String get user_not_found {
    switch (locale.languageCode) {
      case 'en':
        return 'User not found';
      case 'id':
        return 'Pengguna tidak ditemukan';
      case 'es':
        return 'Usuario no encontrado';
      default:
        return 'User not found';
    }
  }
}

/// Translations for home namespace
class _Home {
  _Home(this.locale);

  final Locale locale;

  String get welcome {
    switch (locale.languageCode) {
      case 'en':
        return 'Welcome to Localization Gen!';
      case 'id':
        return 'Selamat datang di Localization Gen!';
      case 'es':
        return '¡Bienvenido a Localization Gen!';
      default:
        return 'Welcome to Localization Gen!';
    }
  }

  String welcome_user({required String name}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Welcome, $name!';
      case 'id':
        return 'Selamat datang, $name!';
      case 'es':
        return '¡Bienvenido, $name!';
      default:
        return 'Welcome, $name!';
    }
  }

  String item_count({required String count}) {
    switch (locale.languageCode) {
      case 'en':
        return 'You have $count items';
      case 'id':
        return 'Anda memiliki $count item';
      case 'es':
        return 'Tienes $count artículos';
      default:
        return 'You have $count items';
    }
  }

  String discount({required String value}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Discount $value%';
      case 'id':
        return 'Diskon $value%';
      case 'es':
        return 'Descuento $value%';
      default:
        return 'Discount $value%';
    }
  }
}

/// Translations for settings namespace
class _Settings {
  _Settings(this.locale);

  final Locale locale;

  /// App settings.profile translations
  _SettingsProfile get profile => _SettingsProfile(locale);

  /// App settings.preferences translations
  _SettingsPreferences get preferences => _SettingsPreferences(locale);

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Settings';
      case 'id':
        return 'Pengaturan';
      case 'es':
        return 'Configuración';
      default:
        return 'Settings';
    }
  }
}

/// Translations for settings.profile namespace
class _SettingsProfile {
  _SettingsProfile(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Profile';
      case 'id':
        return 'Profil';
      case 'es':
        return 'Perfil';
      default:
        return 'Profile';
    }
  }

  String get edit_profile {
    switch (locale.languageCode) {
      case 'en':
        return 'Edit Profile';
      case 'id':
        return 'Edit Profil';
      case 'es':
        return 'Editar Perfil';
      default:
        return 'Edit Profile';
    }
  }

  String get change_password {
    switch (locale.languageCode) {
      case 'en':
        return 'Change Password';
      case 'id':
        return 'Ubah Kata Sandi';
      case 'es':
        return 'Cambiar Contraseña';
      default:
        return 'Change Password';
    }
  }
}

/// Translations for settings.preferences namespace
class _SettingsPreferences {
  _SettingsPreferences(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Preferences';
      case 'id':
        return 'Preferensi';
      case 'es':
        return 'Preferencias';
      default:
        return 'Preferences';
    }
  }

  String get language {
    switch (locale.languageCode) {
      case 'en':
        return 'Language';
      case 'id':
        return 'Bahasa';
      case 'es':
        return 'Idioma';
      default:
        return 'Language';
    }
  }

  String get theme {
    switch (locale.languageCode) {
      case 'en':
        return 'Theme';
      case 'id':
        return 'Tema';
      case 'es':
        return 'Tema';
      default:
        return 'Theme';
    }
  }

  String get notifications {
    switch (locale.languageCode) {
      case 'en':
        return 'Notifications';
      case 'id':
        return 'Notifikasi';
      case 'es':
        return 'Notificaciones';
      default:
        return 'Notifications';
    }
  }
}

/// Translations for app namespace
class _App {
  _App(this.locale);

  final Locale locale;

  /// App app.features translations
  _AppFeatures get features => _AppFeatures(locale);

  /// App app.system translations
  _AppSystem get system => _AppSystem(locale);
}

/// Translations for app.features namespace
class _AppFeatures {
  _AppFeatures(this.locale);

  final Locale locale;

  /// App app.features.ecommerce translations
  _AppFeaturesEcommerce get ecommerce => _AppFeaturesEcommerce(locale);

  /// App app.features.social translations
  _AppFeaturesSocial get social => _AppFeaturesSocial(locale);

  /// App app.features.analytics translations
  _AppFeaturesAnalytics get analytics => _AppFeaturesAnalytics(locale);
}

/// Translations for app.features.ecommerce namespace
class _AppFeaturesEcommerce {
  _AppFeaturesEcommerce(this.locale);

  final Locale locale;

  /// App app.features.ecommerce.catalog translations
  _AppFeaturesEcommerceCatalog get catalog =>
      _AppFeaturesEcommerceCatalog(locale);
}

/// Translations for app.features.ecommerce.catalog namespace
class _AppFeaturesEcommerceCatalog {
  _AppFeaturesEcommerceCatalog(this.locale);

  final Locale locale;

  /// App app.features.ecommerce.catalog.products translations
  _AppFeaturesEcommerceCatalogProducts get products =>
      _AppFeaturesEcommerceCatalogProducts(locale);
}

/// Translations for app.features.ecommerce.catalog.products namespace
class _AppFeaturesEcommerceCatalogProducts {
  _AppFeaturesEcommerceCatalogProducts(this.locale);

  final Locale locale;

  /// App app.features.ecommerce.catalog.products.categories translations
  _AppFeaturesEcommerceCatalogProductsCategories get categories =>
      _AppFeaturesEcommerceCatalogProductsCategories(locale);
}

/// Translations for app.features.ecommerce.catalog.products.categories namespace
class _AppFeaturesEcommerceCatalogProductsCategories {
  _AppFeaturesEcommerceCatalogProductsCategories(this.locale);

  final Locale locale;

  /// App app.features.ecommerce.catalog.products.categories.electronics translations
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronics get electronics =>
      _AppFeaturesEcommerceCatalogProductsCategoriesElectronics(locale);
}

/// Translations for app.features.ecommerce.catalog.products.categories.electronics namespace
class _AppFeaturesEcommerceCatalogProductsCategoriesElectronics {
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronics(this.locale);

  final Locale locale;

  /// App app.features.ecommerce.catalog.products.categories.electronics.subcategories translations
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategories
  get subcategories =>
      _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategories(
        locale,
      );
}

/// Translations for app.features.ecommerce.catalog.products.categories.electronics.subcategories namespace
class _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategories {
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategories(
    this.locale,
  );

  final Locale locale;

  /// App app.features.ecommerce.catalog.products.categories.electronics.subcategories.mobile translations
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobile
  get mobile =>
      _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobile(
        locale,
      );
}

/// Translations for app.features.ecommerce.catalog.products.categories.electronics.subcategories.mobile namespace
class _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobile {
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobile(
    this.locale,
  );

  final Locale locale;

  /// App app.features.ecommerce.catalog.products.categories.electronics.subcategories.mobile.brands translations
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrands
  get brands =>
      _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrands(
        locale,
      );
}

/// Translations for app.features.ecommerce.catalog.products.categories.electronics.subcategories.mobile.brands namespace
class _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrands {
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrands(
    this.locale,
  );

  final Locale locale;

  /// App app.features.ecommerce.catalog.products.categories.electronics.subcategories.mobile.brands.premium translations
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrandsPremium
  get premium =>
      _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrandsPremium(
        locale,
      );
}

/// Translations for app.features.ecommerce.catalog.products.categories.electronics.subcategories.mobile.brands.premium namespace
class _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrandsPremium {
  _AppFeaturesEcommerceCatalogProductsCategoriesElectronicsSubcategoriesMobileBrandsPremium(
    this.locale,
  );

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Premium Mobile Brands';
      case 'id':
        return 'Merek Ponsel Premium';
      case 'es':
        return 'Marcas Premium de Móviles';
      default:
        return 'Premium Mobile Brands';
    }
  }

  String get description {
    switch (locale.languageCode) {
      case 'en':
        return 'Discover top-tier mobile devices';
      case 'id':
        return 'Temukan perangkat mobile kelas atas';
      case 'es':
        return 'Descubre dispositivos móviles de primer nivel';
      default:
        return 'Discover top-tier mobile devices';
    }
  }

  String featured_message({required String count}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Featured: $count brands available';
      case 'id':
        return 'Unggulan: $count merek tersedia';
      case 'es':
        return 'Destacado: $count marcas disponibles';
      default:
        return 'Featured: $count brands available';
    }
  }

  String promo({required String discount}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Get $discount% off on premium devices!';
      case 'id':
        return 'Dapatkan diskon $discount% untuk perangkat premium!';
      case 'es':
        return '¡Obtén $discount% de descuento en dispositivos premium!';
      default:
        return 'Get $discount% off on premium devices!';
    }
  }
}

/// Translations for app.features.social namespace
class _AppFeaturesSocial {
  _AppFeaturesSocial(this.locale);

  final Locale locale;

  /// App app.features.social.messaging translations
  _AppFeaturesSocialMessaging get messaging =>
      _AppFeaturesSocialMessaging(locale);
}

/// Translations for app.features.social.messaging namespace
class _AppFeaturesSocialMessaging {
  _AppFeaturesSocialMessaging(this.locale);

  final Locale locale;

  /// App app.features.social.messaging.conversations translations
  _AppFeaturesSocialMessagingConversations get conversations =>
      _AppFeaturesSocialMessagingConversations(locale);
}

/// Translations for app.features.social.messaging.conversations namespace
class _AppFeaturesSocialMessagingConversations {
  _AppFeaturesSocialMessagingConversations(this.locale);

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads translations
  _AppFeaturesSocialMessagingConversationsThreads get threads =>
      _AppFeaturesSocialMessagingConversationsThreads(locale);
}

/// Translations for app.features.social.messaging.conversations.threads namespace
class _AppFeaturesSocialMessagingConversationsThreads {
  _AppFeaturesSocialMessagingConversationsThreads(this.locale);

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads.groups translations
  _AppFeaturesSocialMessagingConversationsThreadsGroups get groups =>
      _AppFeaturesSocialMessagingConversationsThreadsGroups(locale);
}

/// Translations for app.features.social.messaging.conversations.threads.groups namespace
class _AppFeaturesSocialMessagingConversationsThreadsGroups {
  _AppFeaturesSocialMessagingConversationsThreadsGroups(this.locale);

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads.groups.settings translations
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettings get settings =>
      _AppFeaturesSocialMessagingConversationsThreadsGroupsSettings(locale);
}

/// Translations for app.features.social.messaging.conversations.threads.groups.settings namespace
class _AppFeaturesSocialMessagingConversationsThreadsGroupsSettings {
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettings(this.locale);

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads.groups.settings.privacy translations
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacy
  get privacy =>
      _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacy(
        locale,
      );
}

/// Translations for app.features.social.messaging.conversations.threads.groups.settings.privacy namespace
class _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacy {
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacy(
    this.locale,
  );

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads.groups.settings.privacy.permissions translations
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissions
  get permissions =>
      _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissions(
        locale,
      );
}

/// Translations for app.features.social.messaging.conversations.threads.groups.settings.privacy.permissions namespace
class _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissions {
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissions(
    this.locale,
  );

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads.groups.settings.privacy.permissions.roles translations
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRoles
  get roles =>
      _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRoles(
        locale,
      );
}

/// Translations for app.features.social.messaging.conversations.threads.groups.settings.privacy.permissions.roles namespace
class _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRoles {
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRoles(
    this.locale,
  );

  final Locale locale;

  /// App app.features.social.messaging.conversations.threads.groups.settings.privacy.permissions.roles.admin translations
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRolesAdmin
  get admin =>
      _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRolesAdmin(
        locale,
      );
}

/// Translations for app.features.social.messaging.conversations.threads.groups.settings.privacy.permissions.roles.admin namespace
class _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRolesAdmin {
  _AppFeaturesSocialMessagingConversationsThreadsGroupsSettingsPrivacyPermissionsRolesAdmin(
    this.locale,
  );

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Administrator';
      case 'id':
        return 'Administrator';
      case 'es':
        return 'Administrador';
      default:
        return 'Administrator';
    }
  }

  String get description {
    switch (locale.languageCode) {
      case 'en':
        return 'Full access to all group settings';
      case 'id':
        return 'Akses penuh ke semua pengaturan grup';
      case 'es':
        return 'Acceso completo a todas las configuraciones del grupo';
      default:
        return 'Full access to all group settings';
    }
  }

  String grant_permission({required String permission, required String user}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Grant $permission to $user';
      case 'id':
        return 'Berikan $permission kepada $user';
      case 'es':
        return 'Conceder $permission a $user';
      default:
        return 'Grant $permission to $user';
    }
  }

  String get revoke_warning {
    switch (locale.languageCode) {
      case 'en':
        return 'Are you sure you want to revoke access?';
      case 'id':
        return 'Apakah Anda yakin ingin mencabut akses?';
      case 'es':
        return '¿Estás seguro de que quieres revocar el acceso?';
      default:
        return 'Are you sure you want to revoke access?';
    }
  }
}

/// Translations for app.features.analytics namespace
class _AppFeaturesAnalytics {
  _AppFeaturesAnalytics(this.locale);

  final Locale locale;

  /// App app.features.analytics.dashboard translations
  _AppFeaturesAnalyticsDashboard get dashboard =>
      _AppFeaturesAnalyticsDashboard(locale);
}

/// Translations for app.features.analytics.dashboard namespace
class _AppFeaturesAnalyticsDashboard {
  _AppFeaturesAnalyticsDashboard(this.locale);

  final Locale locale;

  /// App app.features.analytics.dashboard.reports translations
  _AppFeaturesAnalyticsDashboardReports get reports =>
      _AppFeaturesAnalyticsDashboardReports(locale);
}

/// Translations for app.features.analytics.dashboard.reports namespace
class _AppFeaturesAnalyticsDashboardReports {
  _AppFeaturesAnalyticsDashboardReports(this.locale);

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics translations
  _AppFeaturesAnalyticsDashboardReportsMetrics get metrics =>
      _AppFeaturesAnalyticsDashboardReportsMetrics(locale);
}

/// Translations for app.features.analytics.dashboard.reports.metrics namespace
class _AppFeaturesAnalyticsDashboardReportsMetrics {
  _AppFeaturesAnalyticsDashboardReportsMetrics(this.locale);

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics.performance translations
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformance get performance =>
      _AppFeaturesAnalyticsDashboardReportsMetricsPerformance(locale);
}

/// Translations for app.features.analytics.dashboard.reports.metrics.performance namespace
class _AppFeaturesAnalyticsDashboardReportsMetricsPerformance {
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformance(this.locale);

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics.performance.charts translations
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceCharts get charts =>
      _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceCharts(locale);
}

/// Translations for app.features.analytics.dashboard.reports.metrics.performance.charts namespace
class _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceCharts {
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceCharts(this.locale);

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries translations
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseries
  get timeseries =>
      _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseries(
        locale,
      );
}

/// Translations for app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries namespace
class _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseries {
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseries(
    this.locale,
  );

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries.data translations
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesData
  get data =>
      _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesData(
        locale,
      );
}

/// Translations for app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries.data namespace
class _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesData {
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesData(
    this.locale,
  );

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries.data.aggregations translations
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregations
  get aggregations =>
      _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregations(
        locale,
      );
}

/// Translations for app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries.data.aggregations namespace
class _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregations {
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregations(
    this.locale,
  );

  final Locale locale;

  /// App app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries.data.aggregations.daily translations
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregationsDaily
  get daily =>
      _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregationsDaily(
        locale,
      );
}

/// Translations for app.features.analytics.dashboard.reports.metrics.performance.charts.timeseries.data.aggregations.daily namespace
class _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregationsDaily {
  _AppFeaturesAnalyticsDashboardReportsMetricsPerformanceChartsTimeseriesDataAggregationsDaily(
    this.locale,
  );

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Daily Performance Metrics';
      case 'id':
        return 'Metrik Kinerja Harian';
      case 'es':
        return 'Métricas de Rendimiento Diario';
      default:
        return 'Daily Performance Metrics';
    }
  }

  String subtitle({required String date}) {
    switch (locale.languageCode) {
      case 'en':
        return 'View detailed analytics for $date';
      case 'id':
        return 'Lihat analitik terperinci untuk $date';
      case 'es':
        return 'Ver análisis detallado para $date';
      default:
        return 'View detailed analytics for $date';
    }
  }

  String summary({required String count}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Total: $count events processed';
      case 'id':
        return 'Total: $count kejadian diproses';
      case 'es':
        return 'Total: $count eventos procesados';
      default:
        return 'Total: $count events processed';
    }
  }

  String export({required String format}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Export data to $format';
      case 'id':
        return 'Ekspor data ke $format';
      case 'es':
        return 'Exportar datos a $format';
      default:
        return 'Export data to $format';
    }
  }
}

/// Translations for app.system namespace
class _AppSystem {
  _AppSystem(this.locale);

  final Locale locale;

  /// App app.system.configuration translations
  _AppSystemConfiguration get configuration => _AppSystemConfiguration(locale);
}

/// Translations for app.system.configuration namespace
class _AppSystemConfiguration {
  _AppSystemConfiguration(this.locale);

  final Locale locale;

  /// App app.system.configuration.network translations
  _AppSystemConfigurationNetwork get network =>
      _AppSystemConfigurationNetwork(locale);
}

/// Translations for app.system.configuration.network namespace
class _AppSystemConfigurationNetwork {
  _AppSystemConfigurationNetwork(this.locale);

  final Locale locale;

  /// App app.system.configuration.network.connections translations
  _AppSystemConfigurationNetworkConnections get connections =>
      _AppSystemConfigurationNetworkConnections(locale);
}

/// Translations for app.system.configuration.network.connections namespace
class _AppSystemConfigurationNetworkConnections {
  _AppSystemConfigurationNetworkConnections(this.locale);

  final Locale locale;

  /// App app.system.configuration.network.connections.protocols translations
  _AppSystemConfigurationNetworkConnectionsProtocols get protocols =>
      _AppSystemConfigurationNetworkConnectionsProtocols(locale);
}

/// Translations for app.system.configuration.network.connections.protocols namespace
class _AppSystemConfigurationNetworkConnectionsProtocols {
  _AppSystemConfigurationNetworkConnectionsProtocols(this.locale);

  final Locale locale;

  /// App app.system.configuration.network.connections.protocols.security translations
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurity get security =>
      _AppSystemConfigurationNetworkConnectionsProtocolsSecurity(locale);
}

/// Translations for app.system.configuration.network.connections.protocols.security namespace
class _AppSystemConfigurationNetworkConnectionsProtocolsSecurity {
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurity(this.locale);

  final Locale locale;

  /// App app.system.configuration.network.connections.protocols.security.encryption translations
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryption
  get encryption =>
      _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryption(
        locale,
      );
}

/// Translations for app.system.configuration.network.connections.protocols.security.encryption namespace
class _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryption {
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryption(
    this.locale,
  );

  final Locale locale;

  /// App app.system.configuration.network.connections.protocols.security.encryption.algorithms translations
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithms
  get algorithms =>
      _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithms(
        locale,
      );
}

/// Translations for app.system.configuration.network.connections.protocols.security.encryption.algorithms namespace
class _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithms {
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithms(
    this.locale,
  );

  final Locale locale;

  /// App app.system.configuration.network.connections.protocols.security.encryption.algorithms.advanced translations
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvanced
  get advanced =>
      _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvanced(
        locale,
      );
}

/// Translations for app.system.configuration.network.connections.protocols.security.encryption.algorithms.advanced namespace
class _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvanced {
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvanced(
    this.locale,
  );

  final Locale locale;

  /// App app.system.configuration.network.connections.protocols.security.encryption.algorithms.advanced.settings translations
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvancedSettings
  get settings =>
      _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvancedSettings(
        locale,
      );
}

/// Translations for app.system.configuration.network.connections.protocols.security.encryption.algorithms.advanced.settings namespace
class _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvancedSettings {
  _AppSystemConfigurationNetworkConnectionsProtocolsSecurityEncryptionAlgorithmsAdvancedSettings(
    this.locale,
  );

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en':
        return 'Advanced Encryption Settings';
      case 'id':
        return 'Pengaturan Enkripsi Lanjutan';
      case 'es':
        return 'Configuración de Cifrado Avanzado';
      default:
        return 'Advanced Encryption Settings';
    }
  }

  String description({required String protocol}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Configure $protocol encryption';
      case 'id':
        return 'Konfigurasi enkripsi $protocol';
      case 'es':
        return 'Configurar cifrado $protocol';
      default:
        return 'Configure $protocol encryption';
    }
  }

  String key_strength({required String bits}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Key strength: $bits bits';
      case 'id':
        return 'Kekuatan kunci: $bits bit';
      case 'es':
        return 'Fuerza de clave: $bits bits';
      default:
        return 'Key strength: $bits bits';
    }
  }

  String status({required String status}) {
    switch (locale.languageCode) {
      case 'en':
        return 'Status: $status';
      case 'id':
        return 'Status: $status';
      case 'es':
        return 'Estado: $status';
      default:
        return 'Status: $status';
    }
  }
}

/// Localization delegate for AppLocalizations
class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .map((l) => l.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

/// Extension for easy access
extension AppLocalizationsExtension on AppLocalizations {
  static const delegate = AppLocalizationsDelegate();
}
