// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by localization_gen

import 'package:flutter/widgets.dart';

/// Strongly-typed localization class for application translations.
///
/// Access translations using:
/// ```dart
/// final appLocalizations = AppLocalizations.of(context);
/// final text = appLocalizations.hello;
/// ```
class AppLocalizations {
  /// Creates a new AppLocalizations instance for the specified locale.
  AppLocalizations(this.locale);

  /// The locale for this localization instance.
  final Locale locale;

  /// Gets the localization instance from BuildContext.
  ///
  /// Example:
  /// ```dart
  /// final appLocalizations = AppLocalizations.of(context);
  /// ```
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  /// All supported locales for this application.
  static const supportedLocales = [
    Locale('en'),
    Locale('id'),
  ];

  /// Translations for the login namespace.
  _Login get login => _Login(locale);

  /// Translations for the register namespace.
  _Register get register => _Register(locale);

  /// Translations for the errors namespace.
  _Errors get errors => _Errors(locale);

  /// Translations for the profile namespace.
  _Profile get profile => _Profile(locale);

  /// Translations for the preferences namespace.
  _Preferences get preferences => _Preferences(locale);

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Settings';
      case 'id': return 'Pengaturan';
      default: return 'Settings';
    }
  }


  String get welcome {
    switch (locale.languageCode) {
      case 'en': return 'Welcome to Localization Gen!';
      case 'id': return 'Selamat datang di Localization Gen!';
      default: return 'Welcome to Localization Gen!';
    }
  }


  String welcome_user({required String name}) {
    switch (locale.languageCode) {
      case 'en': return 'Welcome, \$name!';
      case 'id': return 'Selamat datang, \$name!';
      default: return 'Welcome, {name}!';
    }
  }


  String item_count({required String count}) {
    switch (locale.languageCode) {
      case 'en': return 'You have \$count items';
      case 'id': return 'Anda memiliki \$count item';
      default: return 'You have {count} items';
    }
  }


  String discount({required String value}) {
    switch (locale.languageCode) {
      case 'en': return 'Discount \$value%';
      case 'id': return 'Diskon \$value%';
      default: return 'Discount {value}%';
    }
  }


  String get hello {
    switch (locale.languageCode) {
      case 'en': return 'Hello';
      case 'id': return 'Halo';
      default: return 'Hello';
    }
  }


  String get goodbye {
    switch (locale.languageCode) {
      case 'en': return 'Goodbye';
      case 'id': return 'Selamat tinggal';
      default: return 'Goodbye';
    }
  }


  String get yes {
    switch (locale.languageCode) {
      case 'en': return 'Yes';
      case 'id': return 'Ya';
      default: return 'Yes';
    }
  }


  String get no {
    switch (locale.languageCode) {
      case 'en': return 'No';
      case 'id': return 'Tidak';
      default: return 'No';
    }
  }


  String get save {
    switch (locale.languageCode) {
      case 'en': return 'Save';
      case 'id': return 'Simpan';
      default: return 'Save';
    }
  }


  String get cancel {
    switch (locale.languageCode) {
      case 'en': return 'Cancel';
      case 'id': return 'Batal';
      default: return 'Cancel';
    }
  }


  String get special_chars {
    switch (locale.languageCode) {
      case 'en': return 'Special: @#\$%^&*()_+-=[]{}|;\':",./<>?';
      case 'id': return 'Khusus: @#\$%^&*()_+-=[]{}|;\':",./<>?';
      default: return 'Special: @#\$%^&*()_+-=[]{}|;\':",./<>?';
    }
  }


  String get currency {
    switch (locale.languageCode) {
      case 'en': return 'Price: \$100 €200 £300 ¥400 ₹500';
      case 'id': return 'Harga: \$100 €200 £300 ¥400 ₹500';
      default: return 'Price: \$100 €200 £300 ¥400 ₹500';
    }
  }


  String get math {
    switch (locale.languageCode) {
      case 'en': return 'Math: 2 + 2 = 4, 10 × 5 = 50, π ≈ 3.14, ∞';
      case 'id': return 'Matematika: 2 + 2 = 4, 10 × 5 = 50, π ≈ 3.14, ∞';
      default: return 'Math: 2 + 2 = 4, 10 × 5 = 50, π ≈ 3.14, ∞';
    }
  }


  String get quotes {
    switch (locale.languageCode) {
      case 'en': return 'Single \'quote\' and double "quote" test';
      case 'id': return 'Tanda kutip \'tunggal\' dan "ganda" tes';
      default: return 'Single \'quote\' and double "quote" test';
    }
  }


  String get emoji {
    switch (locale.languageCode) {
      case 'en': return '😀 🎉 ❤️ 🚀 ⭐ 🌟 💡 🔥 ✨ 🎯';
      case 'id': return '😀 🎉 ❤️ 🚀 ⭐ 🌟 💡 🔥 ✨ 🎯';
      default: return '😀 🎉 ❤️ 🚀 ⭐ 🌟 💡 🔥 ✨ 🎯';
    }
  }


  String get symbols {
    switch (locale.languageCode) {
      case 'en': return '© ® ™ € £ ¥ § ¶ † ‡ • ‰ ′ ″';
      case 'id': return '© ® ™ € £ ¥ § ¶ † ‡ • ‰ ′ ″';
      default: return '© ® ™ € £ ¥ § ¶ † ‡ • ‰ ′ ″';
    }
  }


  String get arrows {
    switch (locale.languageCode) {
      case 'en': return '← → ↑ ↓ ↔ ↕ ⇐ ⇒ ⇑ ⇓';
      case 'id': return '← → ↑ ↓ ↔ ↕ ⇐ ⇒ ⇑ ⇓';
      default: return '← → ↑ ↓ ↔ ↕ ⇐ ⇒ ⇑ ⇓';
    }
  }


  String get numbers {
    switch (locale.languageCode) {
      case 'en': return '① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩';
      case 'id': return '① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩';
      default: return '① ② ③ ④ ⑤ ⑥ ⑦ ⑧ ⑨ ⑩';
    }
  }


  String get stars {
    switch (locale.languageCode) {
      case 'en': return '★ ☆ ✪ ✫ ✬ ✭ ✮ ✯ ✰';
      case 'id': return '★ ☆ ✪ ✫ ✬ ✭ ✮ ✯ ✰';
      default: return '★ ☆ ✪ ✫ ✬ ✭ ✮ ✯ ✰';
    }
  }


  String get checkmarks {
    switch (locale.languageCode) {
      case 'en': return '✓ ✔ ✕ ✖ ✗ ✘';
      case 'id': return '✓ ✔ ✕ ✖ ✗ ✘';
      default: return '✓ ✔ ✕ ✖ ✗ ✘';
    }
  }


  String get hearts {
    switch (locale.languageCode) {
      case 'en': return '♥ ♡ ❤ ❥ ❣ ❦ ❧';
      case 'id': return '♥ ♡ ❤ ❥ ❣ ❦ ❧';
      default: return '♥ ♡ ❤ ❥ ❣ ❦ ❧';
    }
  }


  String get music {
    switch (locale.languageCode) {
      case 'en': return '♩ ♪ ♫ ♬ ♭ ♮ ♯';
      case 'id': return '♩ ♪ ♫ ♬ ♭ ♮ ♯';
      default: return '♩ ♪ ♫ ♬ ♭ ♮ ♯';
    }
  }


  String get weather {
    switch (locale.languageCode) {
      case 'en': return '☀ ☁ ☂ ☃ ★ ☆ ☉ ☼ ☽ ☾';
      case 'id': return '☀ ☁ ☂ ☃ ★ ☆ ☉ ☼ ☽ ☾';
      default: return '☀ ☁ ☂ ☃ ★ ☆ ☉ ☼ ☽ ☾';
    }
  }


  String get zodiac {
    switch (locale.languageCode) {
      case 'en': return '♈ ♉ ♊ ♋ ♌ ♍ ♎ ♏ ♐ ♑ ♒ ♓';
      case 'id': return '♈ ♉ ♊ ♋ ♌ ♍ ♎ ♏ ♐ ♑ ♒ ♓';
      default: return '♈ ♉ ♊ ♋ ♌ ♍ ♎ ♏ ♐ ♑ ♒ ♓';
    }
  }


  String get cards {
    switch (locale.languageCode) {
      case 'en': return '♠ ♣ ♥ ♦';
      case 'id': return '♠ ♣ ♥ ♦';
      default: return '♠ ♣ ♥ ♦';
    }
  }


  String get gender {
    switch (locale.languageCode) {
      case 'en': return '♂ ♀ ⚤ ⚥ ⚦ ⚧ ⚨ ⚩';
      case 'id': return '♂ ♀ ⚤ ⚥ ⚦ ⚧ ⚨ ⚩';
      default: return '♂ ♀ ⚤ ⚥ ⚦ ⚧ ⚨ ⚩';
    }
  }


  String get chess {
    switch (locale.languageCode) {
      case 'en': return '♔ ♕ ♖ ♗ ♘ ♙ ♚ ♛ ♜ ♝ ♞ ♟';
      case 'id': return '♔ ♕ ♖ ♗ ♘ ♙ ♚ ♛ ♜ ♝ ♞ ♟';
      default: return '♔ ♕ ♖ ♗ ♘ ♙ ♚ ♛ ♜ ♝ ♞ ♟';
    }
  }


  String get greek {
    switch (locale.languageCode) {
      case 'en': return 'α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω';
      case 'id': return 'α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω';
      default: return 'α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω';
    }
  }


  String get cyrillic {
    switch (locale.languageCode) {
      case 'en': return 'А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я';
      case 'id': return 'А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я';
      default: return 'А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я';
    }
  }


  String get arabic {
    switch (locale.languageCode) {
      case 'en': return 'أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي';
      case 'id': return 'أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي';
      default: return 'أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي';
    }
  }


  String get chinese {
    switch (locale.languageCode) {
      case 'en': return '中文测试 你好世界';
      case 'id': return '中文测试 你好世界';
      default: return '中文测试 你好世界';
    }
  }


  String get japanese {
    switch (locale.languageCode) {
      case 'en': return '日本語テスト こんにちは世界';
      case 'id': return '日本語テスト こんにちは世界';
      default: return '日本語テスト こんにちは世界';
    }
  }


  String get korean {
    switch (locale.languageCode) {
      case 'en': return '한국어 테스트 안녕하세요';
      case 'id': return '한국어 테스트 안녕하세요';
      default: return '한국어 테스트 안녕하세요';
    }
  }


  String get mixed {
    switch (locale.languageCode) {
      case 'en': return 'Hello! 你好 こんにちは 안녕하세요 مرحبا Привет 🌍';
      case 'id': return 'Halo! 你好 こんにちは 안녕하세요 مرحبا Привет';
      default: return 'Hello! 你好 こんにちは 안녕하세요 مرحبا Привет 🌍';
    }
  }


  String get multiline_notice {
    switch (locale.languageCode) {
      case 'en': return 'Your account is temporarily locked for 15 minutes for security reasons.\nYou can try again in.';
      case 'id': return 'Akun Anda terkunci sementara selama 15 menit demi keamanan.\\nAnda dapat mencoba lagi dalam.';
      default: return 'Your account is temporarily locked for 15 minutes for security reasons.\nYou can try again in.';
    }
  }


  String get multiline_sample {
    switch (locale.languageCode) {
      case 'en': return 'Line 1\nLine 2';
      case 'id': return 'Baris 1\\nBaris 2';
      default: return 'Line 1\nLine 2';
    }
  }


}

/// Translations for login namespace
class _Login {
  _Login(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Login';
      case 'id': return 'Masuk';
      default: return 'Login';
    }
  }


  String get email {
    switch (locale.languageCode) {
      case 'en': return 'Email';
      case 'id': return 'Email';
      default: return 'Email';
    }
  }


  String get password {
    switch (locale.languageCode) {
      case 'en': return 'Password';
      case 'id': return 'Kata Sandi';
      default: return 'Password';
    }
  }


  String get button {
    switch (locale.languageCode) {
      case 'en': return 'Sign In';
      case 'id': return 'Masuk';
      default: return 'Sign In';
    }
  }


  String get forgot_password {
    switch (locale.languageCode) {
      case 'en': return 'Forgot Password?';
      case 'id': return 'Lupa Kata Sandi?';
      default: return 'Forgot Password?';
    }
  }


}

/// Translations for register namespace
class _Register {
  _Register(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Register';
      case 'id': return 'Daftar';
      default: return 'Register';
    }
  }


  String get button {
    switch (locale.languageCode) {
      case 'en': return 'Sign Up';
      case 'id': return 'Buat Akun';
      default: return 'Sign Up';
    }
  }


  String get terms_accept {
    switch (locale.languageCode) {
      case 'en': return 'I accept the terms and conditions';
      case 'id': return 'Saya menerima syarat dan ketentuan';
      default: return 'I accept the terms and conditions';
    }
  }


}

/// Translations for errors namespace
class _Errors {
  _Errors(this.locale);

  final Locale locale;

  String get invalid_email {
    switch (locale.languageCode) {
      case 'en': return 'Invalid email address';
      case 'id': return 'Alamat email tidak valid';
      default: return 'Invalid email address';
    }
  }


  String get weak_password {
    switch (locale.languageCode) {
      case 'en': return 'Password is too weak';
      case 'id': return 'Kata sandi terlalu lemah';
      default: return 'Password is too weak';
    }
  }


  String get user_not_found {
    switch (locale.languageCode) {
      case 'en': return 'User not found';
      case 'id': return 'Pengguna tidak ditemukan';
      default: return 'User not found';
    }
  }


}

/// Translations for profile namespace
class _Profile {
  _Profile(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Profile';
      case 'id': return 'Profil';
      default: return 'Profile';
    }
  }


  String get edit_profile {
    switch (locale.languageCode) {
      case 'en': return 'Edit Profile';
      case 'id': return 'Edit Profil';
      default: return 'Edit Profile';
    }
  }


  String get change_password {
    switch (locale.languageCode) {
      case 'en': return 'Change Password';
      case 'id': return 'Ubah Kata Sandi';
      default: return 'Change Password';
    }
  }


}

/// Translations for preferences namespace
class _Preferences {
  _Preferences(this.locale);

  final Locale locale;

  String get title {
    switch (locale.languageCode) {
      case 'en': return 'Preferences';
      case 'id': return 'Preferensi';
      default: return 'Preferences';
    }
  }


  String get language {
    switch (locale.languageCode) {
      case 'en': return 'Language';
      case 'id': return 'Bahasa';
      default: return 'Language';
    }
  }


  String get theme {
    switch (locale.languageCode) {
      case 'en': return 'Theme';
      case 'id': return 'Tema';
      default: return 'Theme';
    }
  }


  String get notifications {
    switch (locale.languageCode) {
      case 'en': return 'Notifications';
      case 'id': return 'Notifikasi';
      default: return 'Notifications';
    }
  }


}

/// Localization delegate for AppLocalizations
class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .map((l) => l.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

/// Extension for easy access
extension AppLocalizationsExtension on AppLocalizations {
  static const delegate = AppLocalizationsDelegate();
}

